pipeline {
    agent {label "JAVA-11"}
    stages {
        stage("url") {
            steps {
                git url: "https://github.com/yaradesikasirao/terraform2.git",
                  branch: "main"
            }
        }
        stage("init") {
            steps {
                sh "terraform init"
            }
        }
        stage("validate") {
            steps {
                sh "terraform validate"
            }
        }
        stage("autoapprove") {
            steps {
                sh "terraform apply --auto-approve"
            }
        }
    }
}